name: Sync on DOM Cloud
'on':
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: '{"commands":["curl -LO https://github.com/chrsrns/projects-rust-server/releases/download/latest/release.zip", "unzip release.zip -d .", "cp -r release/* ~/public_html/"]}'
