name: Rust Build to Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r --target=x86_64-unknown-linux-gnu
    - name: Run tests
      run: cargo test
    - name: Compress Directory
      uses: somaz94/compress-decompress@v1
      with:
        command: compress
        source: ./target/x86_64-unknown-linux-gnu/release
        format: zip
    - name: List files
      run: |
        ls .
        ls ./target/x86_64-unknown-linux-gnu/
        ls ./target/x86_64-unknown-linux-gnu/release
