name: Rust Build to Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    environment: "For Actions"

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r --target=x86_64-unknown-linux-gnu
    - name: Run tests
      run: cargo test
    - name: Compress Directory
      uses: somaz94/compress-decompress@v1
      with:
        command: compress
        source: ./target/x86_64-unknown-linux-gnu/release
        format: zip
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          target/x86_64-unknown-linux-gnu/release.zip
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: https://my.domcloud.co/api/githubdeploy
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
        data: '{"commands":["curl -LO https://github.com/chrsrns/projects-rust-server/releases/download/latest/release.zip", "unzip release.zip -d .", "cp -r release/* ~/public_html/"]}'
